# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
from = "/"
to = "/.dist/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/.dist/404.html"
status = 404
